# Generated by Django 6.0.4 on 2026-04-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgrecord',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='predicted_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='short_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
